py: install_deps> python -I -m pip install pytest pytest-cov pytest-mock
.pkg: install_requires> python -I -m pip install 'setuptools>=46.4.0' versioningit
.pkg: _optional_hooks> python /home/circleci/.pyenv/versions/3.8.16/lib/python3.8/site-packages/pyproject_api/_backend.py True setuptools.build_meta
.pkg: get_requires_for_build_sdist> python /home/circleci/.pyenv/versions/3.8.16/lib/python3.8/site-packages/pyproject_api/_backend.py True setuptools.build_meta
.pkg: freeze> python -m pip freeze --all
.pkg: importlib-metadata==6.6.0,packaging==23.1,pip==23.1.2,setuptools==67.7.2,tomli==2.0.1,versioningit==2.2.0,wheel==0.40.0,zipp==3.15.0
.pkg: prepare_metadata_for_build_wheel> python /home/circleci/.pyenv/versions/3.8.16/lib/python3.8/site-packages/pyproject_api/_backend.py True setuptools.build_meta
.pkg: build_sdist> python /home/circleci/.pyenv/versions/3.8.16/lib/python3.8/site-packages/pyproject_api/_backend.py True setuptools.build_meta
py: install_package_deps> python -I -m pip install 'PyYAML>=5.0' 'click-loglevel~=0.2' 'click>=7.0' 'in-place~=0.4' 'pydantic~=1.7' 'python-dateutil~=2.7' 'python-dotenv<2.0,>=0.11' 'requests~=2.20'
py: install_package> python -I -m pip install --force-reinstall --no-deps /home/circleci/project/.tox/.tmp/package/1/tinuous-0.6.1.post35+g970ee5b.tar.gz
py: freeze> python -m pip freeze --all
py: certifi==2023.5.7,charset-normalizer==3.1.0,click==8.1.3,click-loglevel==0.4.0.post1,coverage==7.2.5,exceptiongroup==1.1.1,idna==3.4,in-place==0.5.0,iniconfig==2.0.0,packaging==23.1,pip==23.1.2,pluggy==1.0.0,pydantic==1.10.7,pytest==7.3.1,pytest-cov==4.0.0,pytest-mock==3.10.0,python-dateutil==2.8.2,python-dotenv==1.0.0,PyYAML==6.0,requests==2.30.0,setuptools==67.7.2,six==1.16.0,tinuous @ file:///home/circleci/project/.tox/.tmp/package/1/tinuous-0.6.1.post35%2Bg970ee5b.tar.gz#sha256=de111f715943c7c6a396f955abfa319b640cbfa7d833cdb36af7041004fe7e8e,tomli==2.0.1,typing_extensions==4.5.0,urllib3==2.0.2,wheel==0.40.0
py: commands[0]> tinuous --help
Traceback (most recent call last):
  File "/home/circleci/project/.tox/py/bin/tinuous", line 5, in <module>
    from tinuous.__main__ import main
  File "/home/circleci/project/.tox/py/lib/python3.8/site-packages/tinuous/__main__.py", line 18, in <module>
    from .config import Config, GHPathsDict
  File "/home/circleci/project/.tox/py/lib/python3.8/site-packages/tinuous/config.py", line 16, in <module>
    from .travis import Travis
  File "/home/circleci/project/.tox/py/lib/python3.8/site-packages/tinuous/travis.py", line 229, in <module>
    class Commit(BaseModel):
  File "pydantic/main.py", line 178, in pydantic.main.ModelMetaclass.__new__
  File "pydantic/typing.py", line 399, in pydantic.typing.resolve_annotations
    """Special type construct to mark class variables.
  File "/home/circleci/.pyenv/versions/3.8.16/lib/python3.8/typing.py", line 270, in _eval_type
    return t._evaluate(globalns, localns)
  File "/home/circleci/.pyenv/versions/3.8.16/lib/python3.8/typing.py", line 518, in _evaluate
    eval(self.__forward_code__, globalns, localns),
  File "<string>", line 1, in <module>
TypeError: 'type' object is not subscriptable
py: exit 1 (0.23 seconds) /home/circleci/project> tinuous --help pid=336
.pkg: _exit> python /home/circleci/.pyenv/versions/3.8.16/lib/python3.8/site-packages/pyproject_api/_backend.py True setuptools.build_meta
  py: FAIL code 1 (12.06=setup[11.83]+cmd[0.23] seconds)
  evaluation failed :( (12.12 seconds)

Exited with code exit status 1
