2022-01-11T15:47:03.6354259Z ##[group]Run tox -e typing
2022-01-11T15:47:03.6354837Z [36;1mtox -e typing[0m
2022-01-11T15:47:03.6396588Z shell: /usr/bin/bash -e {0}
2022-01-11T15:47:03.6396990Z env:
2022-01-11T15:47:03.6397508Z   pythonLocation: /opt/hostedtoolcache/Python/3.8.12/x64
2022-01-11T15:47:03.6398231Z   LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.8.12/x64/lib
2022-01-11T15:47:03.6398748Z ##[endgroup]
2022-01-11T15:47:04.4383480Z .package create: /home/runner/work/tinuous/tinuous/.tox/.package
2022-01-11T15:47:04.4932181Z .package installdeps: setuptools >= 46.4.0, wheel ~= 0.32
2022-01-11T15:47:08.3111329Z typing create: /home/runner/work/tinuous/tinuous/.tox/typing
2022-01-11T15:47:08.5636234Z typing installdeps: mypy~=0.900, types-python-dateutil, types-PyYAML, types-requests, pytest~=6.0, pytest-cov~=2.0, pytest-mock~=3.0
2022-01-11T15:47:14.2225739Z typing inst: /home/runner/work/tinuous/tinuous/.tox/.tmp/package/1/tinuous-0.5.0+16.gb9be376.tar.gz
2022-01-11T15:47:22.8186447Z typing installed: attrs==21.4.0,certifi==2021.10.8,cffi==1.15.0,charset-normalizer==2.0.10,click==8.0.3,click-loglevel==0.4.0.post1,coverage==6.2,Deprecated==1.2.13,idna==3.3,in-place==0.5.0,iniconfig==1.1.1,mypy==0.931,mypy-extensions==0.4.3,packaging==21.3,pluggy==1.0.0,py==1.11.0,pycparser==2.21,pydantic==1.9.0,PyGithub==1.55,PyJWT==2.3.0,PyNaCl==1.5.0,pyparsing==3.0.6,pytest==6.2.5,pytest-cov==2.12.1,pytest-mock==3.6.1,python-dateutil==2.8.2,python-dotenv==0.19.2,PyYAML==5.4.1,requests==2.27.1,six==1.16.0,tinuous @ file:///home/runner/work/tinuous/tinuous/.tox/.tmp/package/1/tinuous-0.5.0%2B16.gb9be376.tar.gz,toml==0.10.2,tomli==2.0.0,types-python-dateutil==2.8.6,types-PyYAML==6.0.3,types-requests==2.27.5,types-urllib3==1.26.4,typing_extensions==4.0.1,urllib3==1.26.8,wrapt==1.13.3
2022-01-11T15:47:22.8198458Z typing run-test-pre: PYTHONHASHSEED='763481303'
2022-01-11T15:47:22.8227251Z typing run-test: commands[0] | mypy src test
2022-01-11T15:47:30.3038745Z test/test_state.py:60: error: Statement is unreachable  [unreachable]
2022-01-11T15:47:30.3060636Z         assert statefile.modified
2022-01-11T15:47:30.3087972Z         ^
2022-01-11T15:47:30.3089186Z test/test_state.py:88: error: Statement is unreachable  [unreachable]
2022-01-11T15:47:30.3090062Z         with open(STATE_FILE) as fp:
2022-01-11T15:47:30.3090698Z         ^
2022-01-11T15:47:30.3091466Z test/test_state.py:127: error: Statement is unreachable  [unreachable]
2022-01-11T15:47:30.3092318Z         with f.open() as fp:
2022-01-11T15:47:30.3092887Z         ^
2022-01-11T15:47:30.3093633Z test/test_state.py:164: error: Statement is unreachable  [unreachable]
2022-01-11T15:47:30.3094500Z         with f.open() as fp:
2022-01-11T15:47:30.3095066Z         ^
2022-01-11T15:47:30.4133965Z Found 4 errors in 1 file (checked 13 source files)
2022-01-11T15:47:30.4210565Z ERROR: InvocationError for command /home/runner/work/tinuous/tinuous/.tox/typing/bin/mypy src test (exited with code 1)
2022-01-11T15:47:30.4216912Z ___________________________________ summary ____________________________________
2022-01-11T15:47:30.4217644Z ERROR:   typing: commands failed
2022-01-11T15:47:30.4468617Z ##[error]Process completed with exit code 1.
